name: Build and Deploy Plugin

on:
  push:
    branches:
      - main  # Wird ausgelöst, wenn auf main gepusht wird

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: updateserver

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setze ZIP-Dateinamen basierend auf Repository-Namen (kleingeschrieben)
        run: echo "PLUGIN_NAME=$(basename $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Entferne alte ZIP-Datei (falls vorhanden)
        run: rm -f ${{ env.PLUGIN_NAME }}.zip

      - name: Build ZIP Archive
        run: |
          mkdir -p build
          rsync -av --progress ./ build/ --exclude .git --exclude .github
          cd build
          zip -r ../${{ env.PLUGIN_NAME }}.zip .
          cd ..

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Upload ZIP to Server via SCP (überschreibt vorhandene Datei)
        run: |
          sshpass -p "${{ secrets.SSH_PASS }}" scp -o StrictHostKeyChecking=no $PLUGIN_NAME.zip ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PATH }}

      - name: Notify Deployment Success
        run: echo "✅ Plugin $PLUGIN_NAME erfolgreich hochgeladen!"
